# services/gti_service.py
# app(11).py의 gti_loop 로직 100% 복원 서비스 버전

from datetime import datetime
from services.sheet_service import get_sheets_service, float_try


def safe_float(x):
    """app(11).py 동일한 안전 float 변환"""
    try:
        if x in ["", None, "값없음", "N/A", "-", "null"]:
            return None
        return float(x)
    except:
        return None


def run_gti_core():
    """
    GTI Core Logic
    - genie_predictions (최근 예측 5개)
    - genie_data_v5 (실제 BTC 가격)
    -> deviation 계산
    -> GTI 생성 및 시트 기록
    """

    try:
        service = get_sheets_service()
        sheet_id = service.sheet_id

        # ----------------------------------------
        # 1) 예측 데이터 불러오기
        # ----------------------------------------
        pred_res = service.read_range("genie_predictions!A:N")
        pv = pred_res.get("values", [])

        if len(pv) < 2:
            return {"error": "No prediction data"}

        headers = pv[0]
        last_preds = pv[-5:]  # 최근 5개

        # ----------------------------------------
        # 2) 실제 시장 데이터 (BTC/USD) 불러오기
        # ----------------------------------------
        data_res = service.read_range("genie_data_v5!A:Z")
        dv = data_res.get("values", [])

        if len(dv) < 2:
            return {"error": "No market data"}

        dh = dv[0]
        ld = dv[-1]

        if "BTC/USD" not in dh:
            return {"error": "BTC/USD column not found"}

        actual_price = safe_float(ld[dh.index("BTC/USD")])

        if not actual_price:
            return {"result": "skipped", "reason": "invalid actual price"}

        # ----------------------------------------
        # 3) 각 예측의 편차 계산
        # ----------------------------------------
        deviations = []

        for p in last_preds:
            pred_price = safe_float(p[headers.index("Predicted_Price")])
            if pred_price:
                dev = abs(pred_price - actual_price) / actual_price * 100
                deviations.append(dev)

        if not deviations:
            return {"result": "skipped", "reason": "no valid deviations"}

        avg_dev = round(sum(deviations) / len(deviations), 2)

        # ----------------------------------------
        # 4) GTI 계산
        # ----------------------------------------
        gti_score = max(0, min(100, 100 - avg_dev))
        trend = "Stable" if avg_dev < 2 else "Volatile"

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        gti_id = f"GTI.{now.replace(':','-').replace(' ','_')}"

        # ----------------------------------------
        # 5) 시트에 기록
        # ----------------------------------------
        row_data = [[
            gti_id,
            now,
            "1h",                # Evaluation period
            len(deviations),
            avg_dev,
            gti_score,
            "GTI=(100-AvgDeviation)",
            "Last 5 Predictions",
            trend,
            "Auto-generated by Genie"
        ]]

        service.append("genie_gti_log!A:J", row_data)

        return {
            "result": "logged",
            "GTI_ID": gti_id,
            "GTI_Score": gti_score,
            "Avg_Deviation": avg_dev,
            "Trend": trend
        }

    except Exception as e:
        print("❌ gti_service error:", e)
        return {"error": str(e)}
